version: "3.8"
services:
  video-stream:
    privileged: true
    build:
      context: .
    command: cargo watch -x 'run  --release --bin video-streaming'
    environment:
      - RUST_LOG=warn
      - FRAMERATE=30
    volumes:
      - /app/target
      - /dev/video0:/dev/video0
      - ./video-streaming:/app/video-streaming
    ports:
      - 8080:8080
  web-ui:
    build:
      context: ./web-ui
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./web-ui/src:/app/src
    environment:
      - REACT_APP_USE_LOCALHOST=true
      - REACT_APP_BROWSER_TEST=false
