version: "3.8"
services:
  web-ui:
    build:
      context: ./web-ui
    ports:
      - 3000:3000
    volumes:
      - ./web-ui/src:/app/src
    command: npm start
    environment:
      - REACT_APP_USE_LOCALHOST=false
      - REACT_APP_BROWSER_TEST=false
      - REACT_APP_RASPBERRY_PI_IP=192.168.18.44
